<?php

use App\Models\JobIndustry;
use Illuminate\Database\Seeder;

class JobIndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $industries = [
            'Communications',
            'Technology',
            'Government/Military',
            'Manufacturing',
            'Financial Services',
            'IT Services',
            'Education',
            'Pharma',
            'Real Estate',
            'Consulting',
            'Health Care',
            'Administration',
            'Advertising',
            'Agriculture',
            'Architecture & Construction',
            'Arts & Graphics',
            'Airline - Aviation',
            'Accounting',
            'Automotive',
            'Banking',
            'Biotechnology',
            'Broadcasting',
            'Business Management',
            'Charity',
            'Catering',
            'Customer Service',
            'Chemicals',
            'Construction',
            'Computer',
            'Consumer',
            'Cosmetics',
            'Design',
            'Defence',
            'Electronics',
            'Engineering',
            'Energy and Utilities',
            'Entertainment',
            'Employment - Recruiting - Staffing',
            'Environmental',
            'Exercise - Fitness',
            'Export/Import',
            'Fashion',
            'FMCG/Foods/Beverage',
            'Fertilizers/Pesticides',
            'Furniture',
            'Grocery',
            'Gas',
            'Government & Public Sector',
            'Gems & Jewellery',
            'Human Resources',
            'Hospitality',
            'Hotels and Lodging',
            'HVAC',
            'Hardware',
            'Insurance',
            'Installation',
            'Industrial',
            'Internet Services',
            'Import - Export',
            'Legal',
            'Logistics',
            'Landscaping',
            'Leisure and Sport',
            'Library Science',
            'Marketing',
            'Management',
            'Merchandising',
            'Medical',
            'Media',
            'Metals',
            'Mining',
            'Mortgage',
            'Marine',
            'Maritime',
            'Nonprofit Charitable Organizations',
            'NGO/Social Services',
            'Newspaper',
            'Oil & Gas',
            'Other',
            'Other/Not Classified',
            'Polymer / Plastic / Rubber',
            'Pharma/Biotech/Clinical Research',
            'Public Sector and Government',
            'Printing/Packaging/Publishing',
            'Personal and Household Services',
            'Property & Real Estate',
            'Paper',
            'Pet Store',
            'Public Relations',
            'Retail',
            'Retail & Wholesale',
            'Recreation',
            'Real Estate and Property',
            'Recruitment/Employment Firm',
            'Real Estate/Property Management',
            'Restaurant/Food Services',
            'Rental Services',
            'Research & Development',
            'Repair / Maintenance Services',
            'Sales - Marketing',
            'Science & Technology',
            'Security/Law Enforcement',
            'Shipping/Marine',
            'Security and Surveillance',
            'Sports and Physical Recreation',
            'Staffing/Employment Agencies',
            'Social Services',
            'Sports Leisure & Lifestyle',
            'Semiconductor',
            'Services - Corporate B2B',
            'Travel',
            'Training',
            'Transportation',
            'Telecommunications',
            'Trade and Services',
            'Travel and Tourism',
            'Textiles/Garments/Accessories',
            'Tyres',
            'Utilities',
            'Wireless',
            'Wood / Fibre / Paper',
            'Waste Management',
            'Wholesale Trade/Import-Export'
        ];

        foreach($industries as $industry) {
            JobIndustry::create([
                'name' => $industry
            ]);
        }
    }
}
